cart/urls.py
from django.urls import path, re_path
from cart.views import add_to_cart, cart_home, decrease_cart, increase_cart, remove_from_cart

app_name = 'cart'

urlpatterns = [
    re_path(r'^$', cart_home, name='cart-home'),
    # re_path(r'^decrease-item/<int:pk>/$', decrease_cart, name='decrease-item'),
    # re_path(r'^increase-item/<int:pk>/$', increase_cart, name='increase-item'),
    # re_path(r'^remove-item/int<int:pk>/$', remove_from_cart, name='remove-item'),
    # re_path(r'^add/<int:pk>/$', add_to_cart, name='add'),

]

products/urls.py
from django.urls import re_path
from .views import ProductDetailView, ProductDetailSlugView, ProductListView

app_name = 'products'

urlpatterns = [
    re_path(r'^$', ProductListView.as_view(), name='product_list'),
    # re_path(r'^<int:pk>/$', ProductDetailView.as_view(), name='detailed'),
    # re_path(r'^(?P<slug>[\w-]+)/$', ProductDetailSlugView.as_view()),
]

tothepurpleline/urls.py
from django.contrib import admin
from django.urls import path, include
from django.urls import re_path

from accounts import views
from .views import home_page, contact_page
from accounts.views import *
from django.contrib.auth import views as auth_views
from products.views import ProductListView
from products.views import ProductDetailView
from products.views import ProductFeaturedListView
# from products.views import ProductFeaturedDetailView
from products.views import ProductDetailSlugView
from socials.views import *

from django.conf import settings
from django.conf.urls.static import static

from cart.views import add_to_cart
from cart.views import cart_home, decrease_cart, increase_cart, remove_from_cart

# app_name = 'cart'

urlpatterns = [
    path('', home_page, name='home'),
    path('contact/', contact_page, name='contact'),
    path('register/', RegisterView.as_view(), name='register'),
    path('featured/', ProductFeaturedListView.as_view(), name='featured_list' ),
    # path('featured/<int:pk>', ProductFeaturedDetailView.as_view(), name='featured_detailed'),

    path('logout/', auth_views.LogoutView.as_view(template_name="auth/logout.html"), name='logout'),
    path('login', login_page, name='login'),
    path('admin/', admin.site.urls),
    path('socials/', PostListView.as_view(), name='post-list'),
    path('socials/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    path('socials/edit/<int:pk>/', PostEditView.as_view(), name='post-edit'),
    path('socials/<int:pk>/followers/', ListFollowers.as_view(), name='list-followers'),
    path('socials/delete/<int:pk>/', PostDeleteView.as_view(), name='post-delete'),
    path('socials/<int:post_pk>/comment/delete/<int:pk>/', CommentDeleteView.as_view(), name='comment-delete'),
    path('socials/<int:post_pk>/comment/<int:pk>/like', AddCommentLike.as_view(), name='comment-like'),
    path('socials/<int:post_pk>/comment/<int:pk>/dislike', AddCommentDislike.as_view(), name='comment-dislike'),
    path('socials/<int:pk>/like', AddLike.as_view(), name='like'),
    path('socials/<int:pk>/dislike', AddDislike.as_view(), name='dislike'),
    path('profile/<int:pk>/', ProfileView.as_view(), name='profile'),
    path('profile/edit/<int:pk>/', ProfileEditView.as_view(), name='profile-edit'),
    path('profile/<int:pk>/followers/add', AddFollower.as_view(), name='add-follower'),
    path('profile/<int:pk>/followers/remove', RemoveFollower.as_view(), name='remove-follower'),
    # path('profile/edit/<int:pk>/', views.user_delete, name='delete'),
    path('search/', UserSearch.as_view(), name='profile-search'),

    path('cart/', include(('cart.urls', 'cart'), namespace='cart')),
    path('payment/', include(('payment.urls', 'payment'), namespace='payment')),
    path('products/', include(('products.urls', 'products'), namespace='products')),

    path("__reload__/", include('django_browser_reload.urls')),

    # path('products/', ProductListView.as_view(), name='product_list'),
    path('products/<int:pk>/', ProductDetailView.as_view(), name='detailed'),
    re_path(r'^(?P<slug>[\w-]+)/$', ProductDetailSlugView.as_view()),

    # path('cart/', cart_home, name='cart-home'),
    path('cart/decrease-item/<int:pk>/', decrease_cart, name='decrease-item'),
    path('cart/increase-item/<int:pk>/', increase_cart, name='increase-item'),
    path('cart/remove-item/int<int:pk>/', remove_from_cart, name='remove-item'),
    path('cart/<int:pk>/add', add_to_cart, name='add'),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base/css.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/base/js.css.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/base/navbar.html
<a class="navbar-brand"
        {% if user.is_authenticated %}
   href=""
        {% else %}
   href=""
        {% endif %}>

    <!doctype html>
    <html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!-- Bootstrap CSS -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
              integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
              crossorigin="anonymous">

        <title>hall-wall</title>
    </head>
    <body>

    <div class="container-fluid">
        <nav class="navbar fixed-top  navbar-expand-lg navbar-dark" style="background-color: mediumpurple">
            <div class="container-fluid">

                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                        data-bs-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false"
                        aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <a
                        href="#"
                        class="navbar-brand mb-0 h1">
                    StudyCamp
                </a>
                <button
                        type="button"
                        data-bs-toggle="collapse"
                        data-bs-target="#navbarNav"
                        class="navbar-toggler"
                        aria-controls="navbarNav"
                        aria-expanded="false"
                        aria-label="Toggle navigation"
                >
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div
                        class="collapse navbar-collapse"
                        id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item active">
                            <a href="{% url 'post-list' %}" class="nav-link">
                                Hall-Wall
                            </a>
                        </li>
                        <li class="nav-item active">
                            <a href="{% url 'products:product_list' %}" class="nav-link">
                                MarketPlace
                            </a>
                        </li>
                        <li class="nav-item dropdown">
                            <a href="#" class="nav-link
                    dropdown-toggle"
                               id="navbarDropdown" role="button"
                               data-bs-toggle="dropdown"
                               aria-expanded="false"
                            >
                                others
                            </a>
                            <ul class="dropdown-menu"
                                aria-labelledby="navbarDropdown">
                                {% if user.is_authenticated %}
                                    <li><a href="{% url 'profile' user.profile.pk %}"
                                           class="dropdown-item">Profile</a></li>
                                    <li><a href="{% url 'cart:cart-home' %}"
                                           class="dropdown-item">MyCart</a></li>
                                    <li><a href="{% url 'contact' %}"
                                           class="dropdown-item">Contact</a></li>
                                {% endif %}


                            </ul>
                            {% if user.is_authenticated %}
                                </li>
                                <li class="nav-item active">
                                    <a href="{% url 'logout' %}" class="nav-link">
                                        Log-out
                                    </a>
                                </li>
                            {% endif %}

                    </ul>
                </div>
                <form class="d-flex" method="GET" action="{% url 'profile-search' %}">
                    <div class="input-group">
                        <span class="input-group-text" id="basic-addon1">@</span>
                        <input type="text" class="form-control" placeholder="Username" aria-label="Username"
                               aria-describedby="
        basic-addon1" name="query" value="{{ request.GET.query }}">
                        <button style="border: none; background-color: transparent; box-shadow: none" type="submit"><i
                                class="fa fa-search"></i></button>
                    </div>
                </form>
            </div>
        </nav>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
            crossorigin="anonymous"></script>

    </body>
    </html>


</a>