cart/urls.py
from django.urls import path, re_path
from cart.views import add_to_cart, cart_home, decrease_cart, increase_cart, remove_from_cart

app_name = 'cart'

urlpatterns = [
    re_path(r'^$', cart_home, name='cart-home'),
    # re_path(r'^decrease-item/<int:pk>/$', decrease_cart, name='decrease-item'),
    # re_path(r'^increase-item/<int:pk>/$', increase_cart, name='increase-item'),
    # re_path(r'^remove-item/int<int:pk>/$', remove_from_cart, name='remove-item'),
    # re_path(r'^add/<int:pk>/$', add_to_cart, name='add'),

]

products/urls.py
from django.urls import re_path
from .views import ProductDetailView, ProductDetailSlugView, ProductListView

app_name = 'products'

urlpatterns = [
    re_path(r'^$', ProductListView.as_view(), name='product_list'),
    # re_path(r'^<int:pk>/$', ProductDetailView.as_view(), name='detailed'),
    # re_path(r'^(?P<slug>[\w-]+)/$', ProductDetailSlugView.as_view()),
]

shopping_cart/urls.py
from django.urls import re_path

from .views import add_to_cart, delete_from_cart, order_details, checkout, process_payment, update_transaction_records, success

app_name = 'shopping_cart'

urlpatterns = [
    re_path(r'^add-to-cart/(?P<item_id>[-\w]+)/$', add_to_cart, name="add_to_cart"),
    re_path(r'^order-summary/$', order_details, name="order_summary"),
    re_path(r'^success/$', success, name='purchase_success'),
    re_path(r'^item/delete/(?P<item_id>[-\w]+)/$', delete_from_cart, name='delete_item'),
    re_path(r'^checkout/$', checkout, name='checkout'),
    re_path(r'^payment/(?P<order_id>[-\w]+)/$', process_payment, name='process_payment'),
    re_path(r'^update-transaction/(?P<order_id>[-\w]+)/$', update_transaction_records, name='update_records'),
]

tothepurpleline/urls.py
from django.contrib import admin
from django.urls import path, include
from django.urls import re_path

from accounts import views
from .views import home_page, contact_page
from accounts.views import *
from django.contrib.auth import views as auth_views
from products.views import ProductListView
from products.views import ProductDetailView
from products.views import ProductFeaturedListView
# from products.views import ProductFeaturedDetailView
from products.views import ProductDetailSlugView
from socials.views import *

from django.conf import settings
from django.conf.urls.static import static

from cart.views import add_to_cart
from cart.views import cart_home, decrease_cart, increase_cart, remove_from_cart

# app_name = 'cart'

urlpatterns = [
    path('', home_page, name='home'),
    path('contact/', contact_page, name='contact'),
    path('register/', RegisterView.as_view(), name='register'),
    path('featured/', ProductFeaturedListView.as_view(), name='featured_list' ),
    # path('featured/<int:pk>', ProductFeaturedDetailView.as_view(), name='featured_detailed'),

    path('logout/', auth_views.LogoutView.as_view(template_name="auth/logout.html"), name='logout'),
    path('login', login_page, name='login'),
    path('admin/', admin.site.urls),
    path('socials/', PostListView.as_view(), name='post-list'),
    path('socials/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    path('socials/edit/<int:pk>/', PostEditView.as_view(), name='post-edit'),
    path('socials/<int:pk>/followers/', ListFollowers.as_view(), name='list-followers'),
    path('socials/delete/<int:pk>/', PostDeleteView.as_view(), name='post-delete'),
    path('socials/<int:post_pk>/comment/delete/<int:pk>/', CommentDeleteView.as_view(), name='comment-delete'),
    path('socials/<int:post_pk>/comment/<int:pk>/like', AddCommentLike.as_view(), name='comment-like'),
    path('socials/<int:post_pk>/comment/<int:pk>/dislike', AddCommentDislike.as_view(), name='comment-dislike'),
    path('socials/<int:pk>/like', AddLike.as_view(), name='like'),
    path('socials/<int:pk>/dislike', AddDislike.as_view(), name='dislike'),
    path('profile/<int:pk>/', ProfileView.as_view(), name='profile'),
    path('profile/edit/<int:pk>/', ProfileEditView.as_view(), name='profile-edit'),
    path('profile/<int:pk>/followers/add', AddFollower.as_view(), name='add-follower'),
    path('profile/<int:pk>/followers/remove', RemoveFollower.as_view(), name='remove-follower'),
    # path('profile/edit/<int:pk>/', views.user_delete, name='delete'),
    path('search/', UserSearch.as_view(), name='profile-search'),

    path('cart/', include(('cart.urls', 'cart'), namespace='cart')),
    path('payment/', include(('payment.urls', 'payment'), namespace='payment')),
    path('products/', include(('products.urls', 'products'), namespace='products')),

    path("__reload__/", include('django_browser_reload.urls')),

    # path('products/', ProductListView.as_view(), name='product_list'),
    path('products/<int:pk>/', ProductDetailView.as_view(), name='detailed'),
    re_path(r'^(?P<slug>[\w-]+)/$', ProductDetailSlugView.as_view()),

    # path('cart/', cart_home, name='cart-home'),
    path('cart/decrease-item/<int:pk>/', decrease_cart, name='decrease-item'),
    path('cart/increase-item/<int:pk>/', increase_cart, name='increase-item'),
    path('cart/remove-item/int<int:pk>/', remove_from_cart, name='remove-item'),
    path('cart/<int:pk>/add', add_to_cart, name='add'),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/models.py
import random
import os

from django.db import models
from django.db.models import Model
from django.db.models import Q
from .utils import unique_slug_generator
from django.db.models.signals import pre_save



def get_filename_ext(filepath):
    base_name = os.path.basename(filepath)
    name, ext = os.path.splitext(base_name)
    return name, ext

def upload_image_path(instance, filename):
    new_filename = random.randint(1, 2541781232)
    name, ext = get_filename_ext(filename)
    final_name = '{new_filename}{ext}'.format(new_filename=new_filename, ext=ext)
    return "products/{new_filename}/{final_name}".format(new_filename=new_filename, final_name=final_name)



class ProductQuerySet(models.query.QuerySet):
    def active(self):
        return self.filter(active=True)
    def featured(self):
        return self.filter(featured=True, active=True)
    def search(self, query):
        lookups = Q(title__icontains=query) | Q(description__icontains=query) | Q(producttag__title__icontains=query)
        return self.filter(lookups).distinct()

class ProductManager(models.Manager):
    def get_queryset(self):
        return ProductQuerySet(self.model, using=self._db)

    def all(self):
        return self.get_queryset().active()

    def featured(self):
        return self.get_queryset().featured()
    def get_by_id(self, id):
        qs = self.get_queryset().filter(id=id)
        if qs.count() == 1:
            return qs.first()
        return None
    def search(self, query):
        return self.get_queryset().active().search(query)


class Product(models.Model):
    title = models.CharField(max_length=50)
    slug = models.SlugField(blank=True, unique=True)
    description = models.TextField()
    price = models.DecimalField(decimal_places=2, max_digits=20, default=10.00)
    image = models.ImageField(upload_to=upload_image_path, null=True, blank=True)
    featured = models.BooleanField(default=False)
    active = models.BooleanField(default=False)

    objects = ProductManager()

    def __str__(self):
        return self.title

    def __unicode__(self):
        return self.title

    def ProductListView(self):
        return self.title

def product_pre_save_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)
pre_save.connect(product_pre_save_receiver, sender=Product)

products/views.py
from products.models import Product
# Create your views here.
from django.views.generic import ListView
from django.views.generic import DetailView
from django.shortcuts import Http404


class ProductListView(ListView):
    queryset = Product.objects.all()
    template_name = "products/list.html"

    def get_queryset(self, *args, **kwargs):
        request = self.request
        return Product.objects.all()


class ProductDetailView(DetailView):
    queryset = Product.objects.all()
    print(queryset)
    template_name = "products/detail.html"

    def get_context_data(self, *args, **kwargs):
        context = super(ProductDetailView, self).get_context_data(*args, **kwargs)
        return context

    def get_queryset(self, *args, **kwargs):
        request = self.request
        pk = self.kwargs.get('pk')
        return Product.objects.filter(pk=pk)


class ProductFeaturedListView(ListView):
    template_name = "products/list.html"

    def get_queryset(self, *args, **kwargs):
        request = self.request
        return Product.objects.all().featured()


class ProductFeaturedDetailView(DetailView):
    queryset = Product.objects.all().featured()
    template_name = "products/featured-detail.html"


class ProductDetailSlugView(DetailView):
    queryset = Product.objects.all()
    template_name = "products/detail.html"

    def get_object(self, *args, **kwargs):
        request = self.request
        slug = self.kwargs.get('slug')

        try:
            instance = Product.objects.get(slug=slug, active=True)
        except Product.DoesNotExist:
            raise Http404("Not Found")
        except Product.MultipleObjectsReturned:
            qs = Product.objects.filter(slug=slug, active=True)
            instance = qs.first()
        except:
            raise Http404("Test Error")
        return instance

templates/products/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Product</title>
    {% include 'base/css.html' %}
    {% include 'base/js.css.html' %}
</head>
<body>
{% include 'base/navbar.html' %}
{% load static %}
<img class="img-thumbnail" src="{{ object.image.url }}"height="50">
{{ objects.title }} <br>
        <details>
                <summary>Info</summary>
                <p>
                        <h5> Description : {{ object.description }}</h3>
                        <h5> Price : {{ object.price }} </h3>

                </p>
	</details>
{#<div class="row">#}
{#    <div class="col-12 col-md-6">#}
{#        {{ objects.title }} <br>#}
{#        {{ object.description }} <br>#}
{#        {% if object.image %}#}
{#            <img src="{{ object.image.url }}">#}
{#        {% elif not object.image %}#}
{#            <img src="{% static 'img/item.jpg' %}">#}
{#        {% endif %}#}
{#    </div>#}
    <div class="col-12 col-md-6">
        <a href="{% url 'add' pk=object.id %}" class="btn btn-lg btn-outline-primary text-uppercase"><i class="fas fa-shopping-cart"></i>Add to Cart</a>
    </div>
</div>


</body>
</html>

templates/products/featured-detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Product</title>
    {% include 'base/css.html' %}
    {% include 'base/js.css.html' %}
</head>
<body>
{% include 'base/navbar.html' %}

{{ objects.title }} <br>
{{ object.description }} <br>
<img src="{{ object.image.url }}">

</body>
</html>

templates/products/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Your Products</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.rtl.min.css" integrity="sha384-OXTEbYDqaX2ZY/BOaZV/yFGChYHtrXH2nyXJ372n2Y8abBhrqacCEe+3qhSHtLjy" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

</head>
<body>
{% include 'base/navbar.html' %}
{% block content %}
    {{ message }}
    <div class="">
    {% for object in object_list %}
        <br>Title: <a href = "{% url 'detailed' object.id %}"> {{ object.title }}</a><br>
        <div class="col-sm-3">
            <p>{{ object.name }}</p>
            <p>Price: P{{ object.price }}</p>
            {% if object in user.profile.materials.all %}
            You own this
            {% elif object in current_order_products %}
            <a href="{% url 'shopping_cart:order_summary' %}" class="btn btn-warning">Go to Cart</a>
            {% else %}
            <a href="{% url 'shopping_cart:add_to_cart' object.id %}" class="btn btn-warning">Add to Cart</a>
            {% endif %}
        </div>
    {% endfor %}
    </div>
{% endblock content %}

</body>
</html>