cart/urls.py
from django.urls import path, re_path
from cart.views import add_to_cart, cart_home, decrease_cart, increase_cart, remove_from_cart

app_name = 'cart'

urlpatterns = [
    re_path(r'^$', cart_home, name='cart-home'),
    # re_path(r'^decrease-item/<int:pk>/$', decrease_cart, name='decrease-item'),
    # re_path(r'^increase-item/<int:pk>/$', increase_cart, name='increase-item'),
    # re_path(r'^remove-item/int<int:pk>/$', remove_from_cart, name='remove-item'),
    # re_path(r'^add/<int:pk>/$', add_to_cart, name='add'),

]

shopping_cart/urls.py
from django.urls import re_path

from .views import add_to_cart, delete_from_cart, order_details, checkout, process_payment, update_transaction_records, success

app_name = 'shopping_cart'

urlpatterns = [
    re_path(r'^add-to-cart/(?P<item_id>[-\w]+)/$', add_to_cart, name="add_to_cart"),
    re_path(r'^order-summary/$', order_details, name="order_summary"),
    re_path(r'^success/$', success, name='purchase_success'),
    re_path(r'^item/delete/(?P<item_id>[-\w]+)/$', delete_from_cart, name='delete_item'),
    re_path(r'^checkout/$', checkout, name='checkout'),
    re_path(r'^payment/(?P<order_id>[-\w]+)/$', process_payment, name='process_payment'),
    re_path(r'^update-transaction/(?P<order_id>[-\w]+)/$', update_transaction_records, name='update_records'),
]

tothepurpleline/urls.py
from django.contrib import admin
from django.urls import path, include
from django.urls import re_path

from accounts import views
from .views import home_page, contact_page
from accounts.views import *
from django.contrib.auth import views as auth_views
from products.views import ProductListView
from products.views import ProductDetailView
from products.views import ProductFeaturedListView
# from products.views import ProductFeaturedDetailView
from products.views import ProductDetailSlugView
from socials.views import *

from django.conf import settings
from django.conf.urls.static import static

from cart.views import add_to_cart
from cart.views import cart_home, decrease_cart, increase_cart, remove_from_cart

# app_name = 'cart'

urlpatterns = [
    path('', home_page, name='home'),
    path('contact/', contact_page, name='contact'),
    path('register/', RegisterView.as_view(), name='register'),
    path('featured/', ProductFeaturedListView.as_view(), name='featured_list' ),
    # path('featured/<int:pk>', ProductFeaturedDetailView.as_view(), name='featured_detailed'),

    path('logout/', auth_views.LogoutView.as_view(template_name="auth/logout.html"), name='logout'),
    path('login', login_page, name='login'),
    path('admin/', admin.site.urls),
    path('socials/', PostListView.as_view(), name='post-list'),
    path('socials/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    path('socials/edit/<int:pk>/', PostEditView.as_view(), name='post-edit'),
    path('socials/<int:pk>/followers/', ListFollowers.as_view(), name='list-followers'),
    path('socials/delete/<int:pk>/', PostDeleteView.as_view(), name='post-delete'),
    path('socials/<int:post_pk>/comment/delete/<int:pk>/', CommentDeleteView.as_view(), name='comment-delete'),
    path('socials/<int:post_pk>/comment/<int:pk>/like', AddCommentLike.as_view(), name='comment-like'),
    path('socials/<int:post_pk>/comment/<int:pk>/dislike', AddCommentDislike.as_view(), name='comment-dislike'),
    path('socials/<int:pk>/like', AddLike.as_view(), name='like'),
    path('socials/<int:pk>/dislike', AddDislike.as_view(), name='dislike'),
    path('profile/<int:pk>/', ProfileView.as_view(), name='profile'),
    path('profile/edit/<int:pk>/', ProfileEditView.as_view(), name='profile-edit'),
    path('profile/<int:pk>/followers/add', AddFollower.as_view(), name='add-follower'),
    path('profile/<int:pk>/followers/remove', RemoveFollower.as_view(), name='remove-follower'),
    # path('profile/edit/<int:pk>/', views.user_delete, name='delete'),
    path('search/', UserSearch.as_view(), name='profile-search'),

    path('cart/', include(('cart.urls', 'cart'), namespace='cart')),
    path('payment/', include(('payment.urls', 'payment'), namespace='payment')),
    path('products/', include(('products.urls', 'products'), namespace='products')),

    path("__reload__/", include('django_browser_reload.urls')),

    # path('products/', ProductListView.as_view(), name='product_list'),
    path('products/<int:pk>/', ProductDetailView.as_view(), name='detailed'),
    re_path(r'^(?P<slug>[\w-]+)/$', ProductDetailSlugView.as_view()),

    # path('cart/', cart_home, name='cart-home'),
    path('cart/decrease-item/<int:pk>/', decrease_cart, name='decrease-item'),
    path('cart/increase-item/<int:pk>/', increase_cart, name='increase-item'),
    path('cart/remove-item/int<int:pk>/', remove_from_cart, name='remove-item'),
    path('cart/<int:pk>/add', add_to_cart, name='add'),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shopping_cart/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User

from socials.models import UserProfile
from products.models import Product


class OrderItem(models.Model):
    product = models.OneToOneField(Product, on_delete=models.SET_NULL, null=True)
    is_ordered = models.BooleanField(default=False)
    date_added = models.DateTimeField(auto_now=True)
    date_ordered = models.DateTimeField(null=True)

    def __str__(self):
        return self.product.name


class Order(models.Model):
    ref_code = models.CharField(max_length=15)
    owner = models.ForeignKey(UserProfile, on_delete=models.SET_NULL, null=True)
    is_ordered = models.BooleanField(default=False)
    items = models.ManyToManyField(OrderItem)
    # payment_details = models.ForeignKey(Payment, null=True)
    date_ordered = models.DateTimeField(auto_now=True)

    def get_cart_items(self):
        return self.items.all()

    def get_cart_total(self):
        return sum([item.product.price for item in self.items.all()])

    def __str__(self):
        return '{0} - {1}'.format(self.owner, self.ref_code)
# Create your models here.

shopping_cart/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.http.response import HttpResponseRedirect

from products.models import Product
from socials.models import UserProfile

from django.urls import reverse_lazy
import datetime
from django.contrib import messages
from shopping_cart.extras import generate_order_id
from shopping_cart.models import OrderItem, Order
from django.contrib.auth.decorators import login_required


def purchased(request):
    my_user_profile = UserProfile.objects.filter(user=request.user).first()
    my_orders = Order.objects.filter(is_ordered=True, owner=my_user_profile)
    context = {
        'my_orders': my_orders
    }

    return render(request, "purchased.html", context)

def get_user_pending_order(request):
    user_profile = get_object_or_404(UserProfile, user=request.user)
    order = Order.objects.filter(owner=user_profile, is_ordered=True)
    if order.exists():
        return order[0]
    return 0

# Create your views here.
@login_required()
def add_to_cart(request, **kwargs):
    user_profile = get_object_or_404(UserProfile, user=request.user)
    product = Product.objects.filter(id=kwargs.get('item_id', "")).first()
    if product in request.user.profile.materials.all():
        messages.info(request, 'You already own this ebook')
        return redirect(reverse('products:product-list'))
    order_item, status = OrderItem.objects.get_or_create(product=product)
    user_order, status = Order.objects.get_or_create(owner=user_profile, is_ordered=True)
    user_order.items.add(order_item)
    if status:
        user_order.ref_code = generate_order_id()
        user_order.save()
    messages.info(request, "item added to cart")
    return redirect(reverse('products:product-list'))


@login_required()
def delete_from_cart(request, item_id):
    item_to_delete = OrderItem.objects.filter(pk=item_id)
    if item_to_delete.exists():
        item_to_delete[0].delete()
        messages.info(request, "Item has been deleted")
    return redirect(reverse('shopping_cart:order_summary'))


@login_required()
def order_details(request, **kwargs):
    existing_order = get_user_pending_order(request)
    context = {
        'order': existing_order
    }
    return render(request, 'shopping_cart/order_summary.html', context)


@login_required()
def checkout(request):
    existing_order = get_user_pending_order(request)
    context = {
        'order': existing_order,
    }
    return render(request, 'shopping_cart/checkout.html', context)


@login_required()
def process_payment(request, order_id):
    return redirect(reverse('shopping_cart:update_records',
                            kwargs={
                                'order_id': order_id,
                            })
                        )


@login_required()
def update_transaction_records(self, order_id):
    order_to_purchase = Order.objects.filter(pk=order_id).first()
    order_to_purchase.is_ordered=True
    order_to_purchase.date_ordered=datetime.datetime.now()
    order_to_purchase.save()

    order_items = order_to_purchase.items.all()
    order_items.update(is_ordered=True, date_ordered=datetime.datetime.now())

    user_profile = get_object_or_404(UserProfile, user=request.user)
    order_products = [item.product for item in order_items]
    user_profile.materials.add(*order_products)
    user_profile.save()

    messages.info(request, "Items have been added to your profile successfully!")
    return HttpResponseRedirect(reverse_lazy('profile', kwargs={'order_id': pk}))


def success(request, **kwargs):
    return render(request, 'shopping_cart/purchase_success.html', pk=generate_order_id() )

templates/shopping_cart/checkout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Product</title>
    {% include 'base/css.html' %}
    {% include 'base/js.css.html' %}
</head>
<body>
{% include 'base/navbar.html' %}

{% load static %}

{% block content %}
<style>
    table.borderless td, table.borderless th{
        border: none !important;
    }
</style>
<section>
    <div class="row" id="tablerow">
        <div class="col-md-4 col-xs-12">
            <div class="panel panel-primary">
                <div class="panel-body">
                    <h5>Enter Voucher Code Below<br><small>Separate Voucher Codes with comma(If more than one)</small></h5>
                    <div>
                        <form action="." method="post">
                            {% csrf_token %}
                            <input type="text" name="voucher_codes" class="form-control" id="voucher_code" required>
                            <input type="hidden" name="order_id" value="{{ order.id }}">
                            <br>
                            <span>
                                <input type="submit" class="btn btn-warning pull-right" value="Apply Voucher">
                            </span>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-8 col-xs-12">
            <table class="table">
                <tr>
                    <td><h4>Order Summary</h4></td>
                </tr>
                <tr>
                    <td>
                        {% for item in order.get_cart_items %}
                            <tr>
                                <td>{{ items }}</td>
                                <td>P {{ item.product.price }}</td>
                            </tr>
                        {% endfor %}
                    </td>
                </tr>
                <tr>
                    <td><strong>Order Total</strong></td>
                    <td><strong>P {{ order.get_cart_total }}</strong></td>
                </tr>
            </table>
                <form method="POST" action="{% url 'shopping_cart:process_payment' order.id %}">
                    {% csrf_token %}
                    <button style="width: 50%; float: left;" class="btn btn-warning">Pay with card</button>
                </form>
                <form method="POST" action="{% url 'shopping_cart:process_payment' order.id %}">
                    {% csrf_token %}
                    <button style="width: 50%; float: right;" class="btn btn-primary">Pay with Paypal</button>
                </form>
        </div>
    </div>
</section>
{% endblock content %}
{% block scripts %}
    <script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
{% endblock scripts %}
</body>
</html>

templates/shopping_cart/order_summary.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Product</title>
    {% include 'base/css.html' %}
    {% include 'base/js.css.html' %}
</head>
<body>
{% include 'base/navbar.html' %}
{% block content %}
<section>
    <div class="row">
        <table class="table table-hover table-bordered text-center">
            <tr class="text-center">
                <th>no.</th>
                <th>Item</th>
                <th>Price</th>
            </tr>
            {% for item in order.get_cart_items %}
                <tf>
                    <td>{{ forloop.counter }}</td>
                    <td>
                        {{ item.product.name }}
                        <span class="pull-right">
                            <a href="{% url 'shopping_cart:delete_item' item.id %}" data-balloon="remove this item from cart" class="text-danger" onclick="return confirm_delete();">
                                <i class="fas fa-trash"></i>
                            </a>
                        </span>
                    </td>
                    <td>{{ item.product.price }}</td>
                </tf>
            {% empty %}
            <tr>
                <td colspan=3>No Items Added</td>
            </tr>
            {% endfor %}
            <tr>
                {% if order.get_cart_total != None %}
                <td colspan=2>
                    <strong class="pull-right">Order Total:</strong>
                </td>
                <td colspan=1>
                    P<strong>{{ order.get_cart_total }}</strong>
                </td>
                {% endif %}
            </tr>
            <tr>
                <td colspan=1>
                    <a href="{% url 'products:product-list' %}" class="btn btn-warning pull-left">
                        {% if order %}
                        Continue Shopping
                        {% else %}
                        Add Items to Cart
                        {% endif %}
                    </a>
                </td>
                <td colspan=2>
                    {% if order.get_cart_items %}
                        <a href="{% url 'shopping_cart:checkout' %}" class="pull-right btn btn-primary">Proceed To Checkout</a>
                    {% endif %}
                </td>
            </tr>
        </table>
    </div>
</section>
{% endblock %}
{% block scripts %}
    <script>
        function confirm_delete(){
            return confirm("Are you sure you want to delete this item from cart?");
        }
    </script>
{% endblock scripts %}
</body>
</html>

templates/shopping_cart/purchased.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Purchased</title>
    {% include 'base/css.html' %}
    {% include 'base/js.css.html' %}
</head>
<body>
{% include 'base/navbar.html' %}
{% extends 'base.html' %}

{% block content %}

<table class="table table-hover table-bordered text-center">
      <tr class="text-center">
        <th>Date Ordered</th>
        <th>Reference Code</th>
        <th>Items</th>
        <th>Price</th>
      </tr>
      {% for order in my_orders %}
        <tr>
          <td>{{ order.date_ordered }}</td>
          <td>{{ order.ref_code }}</td>
          <td>
        	{% for item in order.items.all %}
        		{{ item.product.name }}
      		{% endfor %}
      	  </td>
          <td>${{ order.get_cart_total }}</td>

        </tr>
      {% empty %}
        <tr>
          <td colspan= 4> You have no orders.</td>
        </tr>
      {% endfor %}

      <tr>
        <td colspan=4>
          <a href="{% url 'products:product-list' %}" class="btn btn-warning pull-left">
            {% if not order %}Continue Shopping{% else %}Add Items to Cart {% endif %}
          </a>
        </td>
      </tr>
    </table>

{% endblock content %}
</body>
</html>